
services:
  ms_analysis:
    
    #the below section is for building the raw image 
    # from scratch. uncomment them if necessary.
    #build: 
    #    context: .
    #    dockerfile: Dockerfile_Jupyter
    #    args:
    #       NB_USER_NEW: "feng"
    #       NB_UID_NEW: "1000"
    image: ffeng23/ms_analysis
    
    # #Do this to get latest one from pushed images online.
    #image: ffeng23/ihc_proximity_jupyter
    environment:
        #- NB_USER= "feng"
        - NB_UID= 1000
        - gid= 1000
        - CHOWN_HOME= yes
        - CHOWN_HOME_OPT= '-R'
        
    #command: bash
    
    #set the new user id 1005, so that the rstudio /init script 
    #will change everyting in the user home directory
    #so means we need to put our project directory in the user home directory
    #here would also set up the .env to have USER id read it
    # USERID: ${UID}
    #.env
    # UID=1005 
    #
    #environment:
    #    NB_USER: "feng"
    #    NB_UID: 1000
    #    CHOWN_HOME: yes
    #CHOWN_HOME_OPTS: '-R'
    #   NB_GID : 1000
    #   NB_GROUP: "feng"
    #do it on my own
    
    #entrypoint: 
    #   - /bin/bash
    #   - -c
    #   - |
    #     #echo "export PATH=/opt/conda/bin:$$PATH" >> /home/feng/.bashrc
    #     echo "run........"
    #     source .bashrc 
    #     apt-get install -y gosu
    #     gosu feng jupyter-lab --ip 0.0.0.0 --port 8888 --no-browser --allow-root
         
         
    
    user : root   

    ports:
       - 8888:8888
       
    #working_dir: /home/jovyan/
    volumes:
      - .:/home/jovyan/ms_analysis
      - vol_msAnalysis_jupyter:/home/feng/ms_analysis/renv
    stdin_open: true 
    tty: true

volumes:
    vol_msAnalysis_jupyter:
    
## to call it.
# run the following
# docker compose -f docker-compose_Jupyter.yml up -d
# docker compose -f docker-compose_Jupyter.yml exec ms_analysis su - feng 
# this will
