
services:
  ms_analysis:
    
    #the below section is for building the raw image 
    # from scratch. uncomment them if necessary.
    build: 
        context: .
        dockerfile: Dockerfile_Jupyter
    
    image: ms_analysis
    # #Do this to get latest one from pushed images online.
    #image: ffeng23/ihc_proximity_jupyter
    #environment:
    #    - user= feng
    #    - uid= 1000
    #    - gid= 1000
    #command: bash
    
    #set the new user id 1005, so that the rstudio /init script 
    #will change everyting in the user home directory
    #so means we need to put our project directory in the user home directory
    #here would also set up the .env to have USER id read it
    # USERID: ${UID}
    #.env
    # UID=1005 
    #
    environment:
       NB_USER: "feng"
       NB_UID: 1000
       CHOWN_HOME: yes
       
    user : root   

    ports:
       - 8888:8888
       
    #working_dir: /main
    volumes:
      - .:/home/feng/ms_analysis
    #stdin_open: true 
    #tty: true

volumes:
    vol_ihc_jupyter:
