
services:
  ms_analysis:
    
    #the below section is for building the raw image 
    # from scratch. uncomment them if necessary.
    build: 
        context: .
        dockerfile: Dockerfile_Jupyter
        args:
           NB_USER: "my-user"
           NB_UID: "1000"
    #image: ffeng23/ms_analysis
    # #Do this to get latest one from pushed images online.
    #image: ffeng23/ihc_proximity_jupyter
    #environment:
    #    - user= feng
    #    - uid= 1000
    #    - gid= 1000
    #command: bash
    
    #set the new user id 1005, so that the rstudio /init script 
    #will change everyting in the user home directory
    #so means we need to put our project directory in the user home directory
    #here would also set up the .env to have USER id read it
    # USERID: ${UID}
    #.env
    # UID=1005 
    #
    #environment:
    #   NB_USER: "feng"
    #   NB_UID: 1000
    #   CHOWN_HOME: yes
    #   CHOWN_HOME_OPTS: '-R'
    #   NB_GID : 1000
    #   NB_GROUP: "feng"
    #do it on my own
    entrypoint:
        - /bin/bash 
        - -c 
        - |
          echo 'managing user account .....'
         
          if [ ! $(getent group ${USER_dock}) ]; then
             echo "adding group now........"
             addgroup --gid ${GID} ${USER_dock}
          fi
          
          #first we need to check whether there is the specified user id.
          echo "the default user id, $(id -u jovyan)"
          if [  $(id -u jovyan ) == ${UID} ];  then
             echo "need to modifying the exist accout with ${UID} to new name...."
             usermod -l ${USER_dock} jovyan
             echo "done modifying......."
          else #we could assume in this case, it doesn't exist a uid as input
             
             echo "modifying........"
             
             usermod -l ${USER_dock} jovyan
             echo "done username"
             
             usermod -u ${UID} ${USER_dock}
             echo "done uid"
             groupmod -g ${GID} ${USER_dock}
             echo "$(id)"
          fi
          echo 'change the owner ship of necessary files' 
          chown -R ${UID}:${GID} ${DIR_TO_CHANGE}
          echo 'Calling the services..........'
          pwd
          
          
          su - ${USER_dock} && export PATH=${CONDA_DIR}/bin:$PATH && source ${CONDA_DIR}/etc/profile.d/conda.sh && conda activate base && jupyter-lab
          
          #su - ${USER_dock} /opt/conda/bin/jupyter-lab
          #echo 'DONE'
    
    
    user : root   

    ports:
       - 8888:8888
       
    #working_dir: /main
    volumes:
      #- .:/home/feng/ms_analysis
      - vol_ihc_jupyter:/home/feng/ms_analysis
    stdin_open: true 
    tty: true

volumes:
    vol_ihc_jupyter:
